// <auto-generated />
using System;
using AspireTodo.ApiService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspireTodo.ApiService.Migrations
{
    [DbContext(typeof(TicketContext))]
    [Migration("20260203231002_initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("AspireTodo.ApiService.Models.TicketItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TicketItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e455f48f-35d1-4fa4-aaf1-4f7fcf5da22a"),
                            CreatedBy = "Sam Sample",
                            CreatedDate = new DateTime(2026, 2, 3, 23, 10, 1, 772, DateTimeKind.Utc).AddTicks(8216),
                            Description = "I experienced an issue with my recent order.",
                            Subject = "Problem with order #1234"
                        },
                        new
                        {
                            Id = new Guid("0c30022b-8617-47ec-8e2d-6f327f507084"),
                            CreatedBy = "Sam Sample",
                            CreatedDate = new DateTime(2026, 2, 3, 23, 10, 1, 772, DateTimeKind.Utc).AddTicks(8664),
                            Description = "Jane Smith's account has issues.",
                            Subject = "Account issue"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
